- id: '1644549022540'
  alias: Home - Evening (Late)
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: alarm_control_panel.alarm_arm_home
    data: {}
    target:
      entity_id: alarm_control_panel.home_alarm_control_panel_alarm_control_panel
  mode: single
- id: '1644569882133'
  alias: Home - Morning (Early)
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '-30'
  condition: []
  action:
  - service: alarm_control_panel.alarm_disarm
    data: {}
    target:
      entity_id: alarm_control_panel.home_alarm_control_panel_alarm_control_panel
  - service: light.turn_on
    data:
      transition: 10
      brightness_pct: 15
    target:
      entity_id: light.main_floor
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.living_room_shades
  mode: single
- id: '1644838194497'
  alias: Master Bedroom - Motion Lights
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 148b73a92c10a65eecd712fdf8958173
    entity_id: binary_sensor.master_motion_ias_zone
    domain: binary_sensor
  condition:
  - condition: numeric_state
    entity_id: sensor.master_motion_illuminance
    below: '10'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 20
    target:
      entity_id: light.master_bedroom_accent_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.master_bedroom_accent_lights
  mode: single
- id: '1644905742835'
  alias: Gym - Lights Button
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Gym Button
    payload: press
    value_template: '{{ value_json.action }}'
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.gym
  mode: single
- id: '1646099971103'
  alias: Amit's Office - Lights Button
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Amit's Office Button
    payload: press
    value_template: '{{ value_json.action }}'
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.upstair_s_office
  mode: single
- id: '1648092253420'
  alias: Home - Evening (Early)
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.living_room_shades
  mode: single
- id: '1648433962952'
  alias: Master Bathroom - Lights Switch
  use_blueprint:
    path: jerelabs/zwave-js-inovelli-lzw31-sn-red-series-dimmer.yaml
    input:
      inovelli_switch: 38f47cfb5deb31095d26375922c49ae8
      button_a:
      - service: light.turn_on
        data:
          brightness_pct: 100
          kelvin: 2600
        target:
          entity_id: light.master_bathroom_lights
      - service: switch.turn_on
        data: {}
        target:
          entity_id:
          - switch.master_bath_fan
          - switch.master_bathroom_tub_switch
      button_b:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.master_bathroom_lights
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
          - switch.master_bath_fan
          - switch.master_bathroom_tub_switch
      button_a2:
      - service: scene.turn_on
        target:
          entity_id: scene.master_bathroom_relax
        metadata: {}
- id: '1649010072406'
  alias: Front Door - Motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_motion
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 255
    target:
      entity_id: light.front_porch_overhead_light
  - wait_for_trigger: []
    timeout: '300'
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.front_porch_overhead_light
  mode: single
- id: '1649170382940'
  alias: Laundy - Washing Machine Timer
  description: Start the timer for how long the washing machine is running.
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Washing Machine Button
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.action == "single" }}'
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.washing_machine
      - service: input_datetime.set_datetime
        data:
          datetime: '{{ now() }}'
        target:
          entity_id: input_datetime.washing_machine
    - conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.action == "double" }}'
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.washing_machine
    default: []
  mode: single
- id: '1650005656504'
  alias: Home Manager - Notify
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - event: HOME_MANAGER_NOTIFY
    event_data: {}
  mode: single
- id: '1650075028373'
  alias: Front Door - Doorbell ding
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_ding
    from: 'off'
    to: 'on'
  condition: []
  action: []
  mode: single
- id: '1651621760847'
  alias: Stairway - Motion Sensor
  description: ''
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Stairway Motion Sensor
    payload: true
    value_template: '{{ value_json.occupancy }}'
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: stairway_current
      snapshot_entities: light.stairs_main_lights
  - service: light.turn_on
    data:
      brightness_pct: 30
    target:
      entity_id: light.stairs_main_lights
  - wait_for_trigger:
    - platform: mqtt
      topic: zigbee2mqtt/Stairway Motion Sensor
      payload: false
      value_template: '{{ value_json.occupancy }}'
    timeout: 00:01:00
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.stairway_current
  mode: single
- id: '1651640832411'
  alias: Master Bedroom - Nightstand Button
  description: ''
  use_blueprint:
    path: Drafted/aqara-buttons-all-in-one-zigbee2mqtt.yaml
    input:
      action_sensor: sensor.master_bedroom_button_action
      single_action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.master_bedroom_nightstands
- id: '1651717873032'
  alias: Home Assistant Backup
  description: ''
  trigger:
  - platform: time
    at: 02:00:00
  condition: []
  action:
  - service: backup.create
    data: {}
  mode: single
