# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - /config
  media_dirs:
    media: /config/media

# https://www.home-assistant.io/integrations/http/
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.144.0/20

# https://www.home-assistant.io/integrations/frontend/
frontend:
  themes: !include_dir_merge_named themes

sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
  - platform: college_football
    team_id: "TEX"
    name: Texas Longhorns
  - platform: avanza_stock
    stock: 472095
    name: GOOGL
  - platform: avanza_stock
    stock: 3873
    name: MSFT
  - platform: avanza_stock
    stock: 4478
    name: NVDA

wake_on_lan:

# https://www.home-assistant.io/integrations/recorder/
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 10
  exclude:
    domains:
      - device_tracker
      - media_player
      - uptime
      - time_date
      - worldclock
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.glances*
      - sensor.load_*m
      - sensor.time*
      - sensor.uptime*
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.time_utc
      - sensor.beat
      - sensor.espresense_master_bedroom_uptime
      - binary_sensor.espresense_master_bedroom
      - sensor.espresense_gym_uptime
      - binary_sensor.espresense_gym
      - binary_sensor.espresense_kitchen
      - sensor.espresense_kitchen_uptime
      - sensor.espresense_gym_free_mem
      - sensor.memory_free
      - sensor.espresense_master_bedroom_free_mem
      - sensor.espresense_kitchen_free_mem
      - sensor.processor_use

# https://www.home-assistant.io/integrations/sun/
sun:

assist_pipeline:
   debug_recording_dir: /config/www/assist_pipeline/