title: Home
views:
  - path: default_view
    background: var(--background-image)
    title: Home
    icon: mdi:home
    theme: ios-dark-mode-blue-red-alternative
    badges: []
    cards:
      - type: grid
        square: false
        columns: 1
        cards:
          - type: weather-forecast
            entity: weather.home
          - type: thermostat
            entity: climate.living_room
          - type: entities
            entities:
              - entity: sensor.ir_remote_humidity
                name: Living Humidity
              - entity: sensor.ir_remote_temperature
                name: Living Temp
              - entity: sensor.pure_cool_formaldehyde_humidity
                name: Master Humidity
              - entity: sensor.pure_cool_formaldehyde_temperature
                name: Master Temp
              - entity: sensor.upstair_s_office_temperature
                name: Office Temp
            state_color: false
      - type: grid
        cards:
          - type: custom:mushroom-entity-card
            icon: mdi:power
            entity: remote.ir_remote_remote
            secondary_info: none
            tap_action:
              action: call-service
              service: remote.send_command
              service_data:
                device: livingroomtv
                command: power
              target:
                entity_id: remote.ir_remote_remote
            icon_color: white
            name: Living Room TV
          - type: grid
            cards:
              - type: button
                show_icon: true
                show_name: false
                icon: mdi:home
                tap_action:
                  action: call-service
                  service: androidtv.adb_command
                  service_data:
                    command: HOME
                    entity_id: media_player.ccgtv_living_room
              - type: button
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    device: livingroomtv
                    command: up
                  target:
                    entity_id: remote.ir_remote_remote
                icon: mdi:arrow-up-bold
                show_name: false
                show_icon: true
                show_state: false
              - type: custom:mushroom-light-card
                entity: light.bookshelf
                show_brightness_control: true
                icon: mdi:bookshelf
              - type: button
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    device: livingroomtv
                    command: left
                  target:
                    entity_id: remote.ir_remote_remote
                icon: mdi:arrow-left-bold
                show_name: false
              - type: button
                icon: mdi:checkbox-blank-circle
                show_name: false
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    device: livingroomtv
                    command: select
                  target:
                    entity_id: remote.ir_remote_remote
                hold_action:
                  action: more-info
                entity: camera.tv_ambilight
              - type: button
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    device: livingroomtv
                    command: right
                  target:
                    entity_id: remote.ir_remote_remote
                icon: mdi:arrow-right-bold
                show_name: false
              - type: button
                show_name: false
                show_icon: true
                icon: mdi:undo-variant
                tap_action:
                  action: call-service
                  service: androidtv.adb_command
                  service_data:
                    command: BACK
                  target:
                    entity_id: media_player.living_room_ccwgtv
              - type: button
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    device: livingroomtv
                    command: down
                  target:
                    entity_id: remote.ir_remote_remote
                icon: mdi:arrow-down-bold
                show_name: false
              - type: custom:mushroom-light-card
                entity: light.tv_ambilight
                show_brightness_control: true
                use_light_color: true
                name: Ambient
              - type: button
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    device: livingroomtv
                    command: volumedown
                  target:
                    entity_id: remote.ir_remote_remote
                icon: mdi:volume-minus
              - type: button
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    device: livingroomtv
                    command: mute
                  target:
                    entity_id: remote.ir_remote_remote
                icon: mdi:volume-off
              - type: button
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    device: livingroomtv
                    command: volumeup
                  target:
                    entity_id: remote.ir_remote_remote
                icon: mdi:volume-plus
            square: true
          - type: custom:mini-media-player
            name: Living Room
            shortcuts:
              columns: 2
              buttons:
                - name: Prime Video
                  type: service
                  id: androidtv.adb_command
                  service: androidtv.adb_command
                  data:
                    entity_id: media_player.living_room_ccwgtv
                    command: >-
                      am start -a android.intent.action.VIEW -n
                      com.amazon.amazonvideo.livingroom/com.amazon.ignition.IgnitionActivity
                - name: Disney+
                  type: service
                  id: androidtv.adb_command
                  service: androidtv.adb_command
                  data:
                    entity_id: media_player.living_room_ccwgtv
                    command: >-
                      am start -a android.intent.action.VIEW -d 
                      https://www.disneyplus.com/
                - name: CNN
                  type: service
                  id: androidtv.adb_command
                  service: androidtv.adb_command
                  data:
                    entity_id: media_player.living_room_ccwgtv
                    command: >-
                      am start -a android.intent.action.VIEW -d
                      https://tv.youtube.com/watch/PyRp1_3Ql70
                - name: Big Bang Theory
                  type: service
                  id: androidtv.adb_command
                  service: androidtv.adb_command
                  data:
                    entity_id: media_player.living_room_ccwgtv
                    command: >-
                      am start -a android.intent.action.VIEW -d
                      https://play.hbomax.com/page/urn:hbo:page:GXdRsewUPO5uAuwEAABEI:type:series
                - name: Fraiser
                  type: service
                  id: androidtv.adb_command
                  service: androidtv.adb_command
                  data:
                    entity_id: media_player.living_room_ccwgtv
                    command: >-
                      am start -a android.intent.action.VIEW -d
                      https://www.hulu.com/series/frasier-0cb9b63b-de82-4751-99c9-1cb12118ab9d
                - name: Simpsons
                  type: service
                  id: androidtv.adb_command
                  service: androidtv.adb_command
                  data:
                    entity_id: media_player.living_room_ccwgtv
                    command: >-
                      am start -a android.intent.action.VIEW -d
                      https://www.disneyplus.com/series/the-simpsons/3ZoBZ52QHb4x
            entity: media_player.living_room_tv
            hide:
              name: true
              icon: true
              info: false
              power: false
              source: false
              sound_mode: false
              controls: false
              prev: false
              next: false
              play_pause: false
              play_stop: false
              jump: false
              volume: true
              volume_level: false
              mute: false
              progress: false
              runtime: false
              runtime_remaining: false
              artwork_border: false
              power_state: false
              icon_state: false
              shuffle: false
              repeat: false
              state_label: null
            toggle_power: true
            source: full
            artwork: material
            info: scroll
        columns: 1
        square: false
      - type: grid
        cards:
          - type: custom:mushroom-light-card
            entity: light.main_floor
            name: First Floor
            icon: mdi:floor-plan
            layout: horizontal
            show_brightness_control: true
          - type: grid
            cards:
              - type: custom:mushroom-light-card
                entity: light.living_room_main_lights
                name: Living
                show_brightness_control: true
              - type: custom:mushroom-light-card
                entity: light.kitchen_main_lights
                name: Kitchen
                show_brightness_control: true
              - type: custom:mushroom-light-card
                entity: light.breakfast_room_main_lights
                name: Breakfast
                show_brightness_control: true
              - type: custom:mushroom-light-card
                entity: light.kitchen_under_cabinet
                name: Cabinet
                show_brightness_control: true
              - type: custom:mushroom-light-card
                entity: light.kitchen_sink_light
                name: Sink
                show_brightness_control: true
              - type: custom:mushroom-light-card
                entity: light.butler_pantry_main_lights
                show_brightness_control: true
                name: Butler
              - type: custom:mushroom-light-card
                entity: light.dining_room_main_lights
                name: Dining
                show_brightness_control: true
              - type: custom:mushroom-light-card
                entity: light.dining_room_chandelier
                name: Chandelier
                icon: mdi:chandelier
                show_brightness_control: true
              - type: custom:mushroom-light-card
                entity: light.stairs_main_lights
                name: Stairs
                show_brightness_control: true
              - type: custom:mushroom-light-card
                entity: light.front_foyer_main_lights
                show_brightness_control: true
                name: Foyer
              - type: custom:mushroom-alarm-control-panel-card
                entity: >-
                  alarm_control_panel.home_alarm_control_panel_alarm_control_panel
                states: []
                name: Alarm
                layout: horizontal
              - type: custom:mushroom-cover-card
                entity: cover.living_room_shades
                name: Shades
                layout: horizontal
              - type: custom:mushroom-light-card
                entity: light.front_porch_overhead_light
                name: Porch
              - type: custom:mushroom-entity-card
                entity: lock.front_door
            columns: 2
            square: false
        columns: 1
        square: false
      - type: grid
        cards:
          - type: custom:mushroom-light-card
            entity: light.master_bedroom
            name: Master
            icon: mdi:bed
            layout: horizontal
            show_brightness_control: true
          - type: grid
            columns: 2
            square: false
            cards:
              - type: custom:mushroom-light-card
                entity: light.master_bedroom_main_lights
                show_brightness_control: true
                name: Bedroom
                icon: mdi:bed
              - type: custom:mushroom-light-card
                entity: light.master_bedroom_accent_lights
                show_brightness_control: true
                name: Entry
              - type: custom:mushroom-light-card
                entity: light.master_bedroom_nightstands
                show_brightness_control: true
                name: Nightstands
                icon: mdi:floor-lamp
              - type: custom:mushroom-fan-card
                entity: fan.pure_cool_formaldehyde
                icon_animation: true
                show_percentage_control: true
                name: Fan
                show_oscillate_control: true
              - type: custom:mushroom-entity-card
                entity: switch.in_wall_smart_switch
                name: Bath Switch
                icon: mdi:light-switch
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
                vertical: true
              - type: custom:mushroom-light-card
                entity: light.master_bathroom
                icon: mdi:shower
                show_brightness_control: true
                name: Bath
                show_color_control: true
          - type: custom:mushroom-light-card
            entity: light.upstairs
            name: Upstairs
            icon: mdi:floor-plan
            layout: horizontal
            show_brightness_control: true
          - type: grid
            cards:
              - type: custom:mushroom-light-card
                entity: light.upstair_s_office
                show_brightness_control: true
                use_light_color: true
                name: Office
                show_color_temp_control: true
              - type: custom:mushroom-light-card
                entity: light.upstair_s_office_lamp
                name: Office Lamp
                show_brightness_control: true
                show_color_temp_control: true
              - type: custom:mushroom-light-card
                entity: light.gym
                use_light_color: true
                show_brightness_control: true
                show_color_control: true
              - type: custom:mushroom-light-card
                entity: light.hallway
                show_brightness_control: true
            columns: 2
            square: false
        columns: 1
        square: false
